site_name: Tronbyt Docs
site_url: https://tronbyt.com
site_author: Tronbyt
site_description: Tronbyt is an open source connected, smart display that shows weather, stocks, sports, and a whole lot more.

repo_name: !ENV [REPO_NAME, "tronbyt/docs"]
repo_url: !ENV [REPO_URL, "https://github.com/tronbyt/docs"]
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  font: false
  logo: icons/logo.svg
  favicon: icons/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: lucide/file-pen

plugins:
  - search
  - privacy
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - What is Tronbyt?: what-is-tronbyt.md
  - Getting Started: getting-started.md
  - Tronbyt Manager: tronbyt-manager.md
  - Configuration: configuration.md
  - Device Specific Notes: device-notes.md
  - Pixlet:
    - Build for Tronbyt: pixlet/build-for-tronbyt.md
    - Installing Pixlet: pixlet/installing.md
    - Authoring Apps: pixlet/authoring-apps.md
    - Pushing Apps: pixlet/pushing-apps.md
    - Tutorials:
      - Clock App: pixlet/tutorials/clock-app.md
      - Crypto Tracker: pixlet/tutorials/crypto-tracker.md
    - Reference:
      - Widgets: pixlet/reference/widgets.md
      - Modules: pixlet/reference/modules.md
      - Animation: pixlet/reference/animation.md
      - Fonts: pixlet/reference/fonts.md
      - Emoji: pixlet/reference/emoji.md
      - Filters: pixlet/reference/filters.md
      - GIFs: pixlet/reference/gifs.md
      - 2x Apps: pixlet/reference/2x-apps.md
      - Internationalization: pixlet/reference/i18n.md
      - Schema: pixlet/reference/schema/schema.md
    - Publish:
      - Community Apps: pixlet/publish/community-apps.md
      - Publishing Apps: pixlet/publish/publishing-apps.md
      - Modifying Apps: pixlet/publish/modifying-apps.md
      - Advanced: pixlet/publish/advanced.md
      - FAQ: pixlet/publish/faq.md
  - Community:
    - community/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tronbyt
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HxST87KxdK

watch:
  - overrides
